### ISSUE TITLE
SearchEvent.getSelectedItem() returns an Optional that contains a new Optional

### ISSUE THREAD

**Issue by neerup** [wbadam/SearchBox#3]
For some reason the getSelectedItem() returned Optional does not contain the Selected Item but a new Optional so One have to have some really dirty code like:

Object object = event.getSelectedItem().orElse(null);
if (object != null) {
   MyObject as = ((Optional<MyObject>) object).orElse(null);
  System.out.printLn(as.getName());
}
This must be a bug...

**Comment by wbadam** [comment]
Hi, thank you for the bug report, this one is now fixed in `0.1.2` release.
